"""Pre-stored, pre-validated problem bank.

Served instantly (no LLM loop) on onboarding and after a settings change, so the
first problem of a chosen configuration appears immediately and offline.

WHAT THE VERIFIER CAN SOLVE (and therefore what the bank covers):
  SymPy math (verification/math_verifier.py):
    - derivative : any elementary function (polynomials, rationals, trig, exp, log,
                   products / quotients / chain rule)
    - integral   : definite integral over [a, b] of a closed-form elementary function
    - limit      : limit at a point, including resolvable indeterminate forms
    - solve_equation : equations with a unique real solution (trig restricted to an
                   interval so the solution is unique)
    - simplify   : algebraic / trig identities (equivalence of two expressions)
  Physics templates (verification/physics_verifier.py), unit- & realism-checked:
    - kinematics       (u, a, t, v, s)
    - newton_friction  (a, friction, F_applied)
    - work_energy      (work, ke, v)
    - impulse_momentum (impulse, momentum, dv)
    - circular_motion  (ac, force, v)

Every entry in problem_bank.json passed all six verifier checks at build time
(see scripts/build_problem_bank.py). The bank is regenerated by that script, not
edited by hand.
"""
from __future__ import annotations

import json
import random
from functools import lru_cache
from pathlib import Path

_BANK_PATH = Path(__file__).resolve().parent / "problem_bank.json"


@lru_cache(maxsize=1)
def load() -> list[dict]:
    if not _BANK_PATH.exists():
        return []
    return json.loads(_BANK_PATH.read_text())


def skills_covered() -> set[str]:
    return {p["skill"] for p in load()}


def fetch(skill: str, difficulty: int, context_id: str | None = None,
          rng: random.Random | None = None) -> dict | None:
    """Return a pre-validated problem for (skill, difficulty).

    Picks randomly among matching variants for variety; falls back to the nearest
    available difficulty for the skill; returns None if the skill isn't banked.
    """
    rng = rng or random
    bank = [p for p in load() if p["skill"] == skill]
    if not bank:
        return None

    exact = [p for p in bank if p["difficulty"] == difficulty]
    if not exact:
        # Nearest difficulty for this skill.
        nearest = min({p["difficulty"] for p in bank}, key=lambda d: abs(d - difficulty))
        exact = [p for p in bank if p["difficulty"] == nearest]

    # Prefer a context match when one is requested and available.
    if context_id:
        ctx_matches = [p for p in exact if p.get("context_id") == context_id]
        if ctx_matches:
            exact = ctx_matches
    return rng.choice(exact)
